version: "3"
services:
  server:
    build: .
    ports:
      - 1070:1070
    depends_on:
      - "db"
    volumes:
      - webapp-pdf:/var/www/html/pdf
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db_password12
      MYSQL_DATABASE: webapp
    ports:
      - 3306:3306
    volumes:
      - webapp-db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  webapp-db:
  webapp-pdf: